# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240315-111430-fresh-rent

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
# Configuration for Rasa NLU.
language: "fr"

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 200
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100
    constrain_similarities: true

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
    constrain_similarities: true

# Server configuration
server:
  # Port on which to run the server
  port: 5005
